name = "ErrorTypes"
uuid = "7f495686-c6d2-4c77-9e8e-e4c865675f9d"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.2.0"

[deps]
SumTypes = "8e1ec7a9-0e02-4297-b0fe-6433085c89f2"

[compat]
SumTypes = "0.1.1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
