name = "ErrorTypes"
uuid = "7f495686-c6d2-4c77-9e8e-e4c865675f9d"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.4.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
